# Generated by Django 3.2 on 2021-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210418_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
